apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-BCPOC-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t2.large
    desiredCapacity: 2
    ssh: # use existing EC2 Key
      publicKeyName: ekslabadmin
