server:
  port: "${SCS_CMD_PORT:8081}"

kafka:
  bootstrap:
    host: "${BOOTSTRAP_HOST:localhost}"
    port: "${BOOTSTRAP_PORT:9092}"

spring:
  main:
    allow-circular-references: true
  application:
    name: "scs-command"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${POSTGRES_WRITER_DBHOST:localhost}:${POSTGRES_WRITER_DBPORT:5432}/${POSTGRES_WRITER_DBNAME:scs_writedb}"
    username: "${POSTGRES_WRITER_DBUSERNAME:postgres}"
    password: "${POSTGRES_WRITER_DBPASSWORD:v3r44pr1}"
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    generate-ddl: true

axon:
  eventhandling:
    processors:
      documentEntity:
        mode: subscribing
  serializer:
    general: xstream
    messages: jackson
    events: jackson