apiVersion: apps/v1
kind: Deployment
metadata:
  name: scs-command
  namespace: default
spec:
  selector:
    matchLabels:
      app: scs-command
  replicas: 1
  template:
    metadata:
      name: scs-command
      labels:
        app: scs-command
    spec:
      containers:
        - name: scs-command
          image: yauritux/scs-command:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
            - name: POSTGRES_PORT
              value: "5432"
