apiVersion: v1
kind: Service
metadata:
  labels:
    app: lenses
  name: lenses
spec:
  ports:
    - name: lenses
      port: 3030
      protocol: TCP
    - name: lenses-broker
      port: 9092
      protocol: TCP
  selector:
    app: lenses
  type: LoadBalancer
