apiVersion: apps/v1
kind: Deployment
metadata:
  name: lenses
spec:
  selector:
    matchLabels:
      app: lenses
  replicas: 1
  template:
    metadata:
      labels:
        app: lenses
    spec:
      containers:
        - name: lenses
          image: lensesio/box
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3030
              hostPort: 3030
              name: lensesbox
            - containerPort: 9092
              hostPort: 9092
              name: kafkabroker
          env:
            - name: ADV_HOST
              value: "localhost"
            - name: EULA
              value: "https://licenses.lenses.io/download/lensesdl?id=7ff3ce9f-631b-11ec-9ed6-42010af01003"
